name: Convert dot to Mermaid with Script

on:
  workflow_dispatch:
    inputs:
      dot-path:
        description: 'Percorso del file .dot'
        required: true
        default: 'infra/resources/dev/graph.dot'
  # push:
  #   branches:
  #     - feat-poc-ai-graph-generation

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydot

      - name: Convert .dot â†’ .mmd
        run: |
          DOT_FILE="${{ inputs.dot-path }}"
          OUTPUT="${DOT_FILE%.dot}.mmd"
          python infra/resources/dev/dot_to_mermaid.py "$DOT_FILE" > "$OUTPUT"
          echo "Generated $OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: "bundle-mermaid-script"
          path: ./output.mmd
          if-no-files-found: error
          retention-days: 7