name: Deploy Static Site to Azure CDN - TEST

on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow-deploy-cdn-ts

jobs:
  test:
    uses: ./.github/workflows/release-typescript-cdn-deploy-test.yaml
    name: CDN Deploy - DRY RUN
    secrets: inherit
    with:
      workspace_name: "static-test-app"
      storage_account_name: "dxditntestcdnst01"
      resource_group_name: "dx-d-itn-test-rg-01"
      profile_name: "dx-d-itn-test-cdn-01"
      endpoint_name: "dx-d-itn-test-ep-g3dubxcwh7ewfwdb.a02.azurefd.net"
      environment: "infra-dev"